class NodeData:
    def __init__(self, id_: int, code: str, name: str, type_: int):
        self.id = id_  # 0, 1, 2, ...
        self.code = code  # A, B, C, ...
        self.name = name  # given random string
        self.type = type_  # 0 for non-decision node, 1 for decision node
